from enum import Enum

class FaceState(Enum):
    NORMAL = "NORMAL"
    EYES_CLOSED = "EYES CLOSED"
    YAWNING = "YAWNING"
    LOOKING_LEFT = "LOOKING LEFT"
    LOOKING_RIGHT = "LOOKING RIGHT"
    LOOKING_DOWN = "LOOKING DOWN"
    ABSENT = "ABSENT"