app:
  title: WebApplication
  description: ???
  version: 0.0.1
  host: 127.0.0.1
  port: 8080

databases:
  provider: postgresql

  mysql:
    url: mysql://user:password@localhost:3306/template

  postgresql:
    url: postgresql+asyncpg://postgres:123456@localhost:5432/postgres

services:
  provider: redis

  redis: 
  

llm:
  provider: ollama 
  
  ollama: 
    base_url: http://localhost:11434
    model: qwen3-vl:4b-instruct 
    embedding: bge-m3:latest
    options:
      temperature: 0.6
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.1
      num_ctx: 4096
      num_predict: 512
      stop: ["</s>"]

  mistral:
  gemini:
  openrouter:
  grok:

redis:
  url: redis://localhost:6379
  index_name: rag_index

neo4j:
  url: bolt://localhost:7687
  username: neo4j
  password: 12345678
  database: neo4j
  vector_index: vector_index
